sonar.projectKey=abcer-node
sonar.projectName=abcer-node
sonar.host.url=http://localhost:9000
sonar.token=sqa_48bf8c6f313379f8d1819e080ef92e216f0ec8ac

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/*.d.ts,**/dist/**,**/generated/**,**/migrations/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
